name: task_pro_supabase
description: "Professional Task Management App with Clean Architecture and Supabase."
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Backend & Auth
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # UI & UX (Versiones seguras)
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  file_picker: ^8.0.1
  lucide_icons: ^0.257.0  # <--- Versión exacta que nos pidió Flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
